name: Deploy Astro site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
            # ...existing code...
      - name: Set env vars
        run: echo "PUBLIC_YOUTUBE_API_KEY=${{ secrets.PUBLIC_YOUTUBE_API_KEY }}" >> $GITHUB_ENV
      - run: pnpm build
      # ...existing code...
      - run: pnpm install
      - run: pnpm build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./dist
